Script started on 2025-03-12 13:54:41-04:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="131" LINES="50"]
[?2004hmwatt29@compute:~/courses/cs2211/Asn/asn4$ ./bs[C_tree < test1.txt
[?2004l100 1st Street    $1000
8 3 Valleys Place    $2000
74 3rd Street    $3000
4 4 Oaks Crescent    $2100
10 Abbott Street    $2300
204 Beech Drive    $1800
36 Beechbank Crescent    $2400
36 Beechmount Crescent    $2500
46 Oxford Street    $2600
70 Oxford Street    $2500
101 Western Road    $2500
[?2004hmwatt29@compute:~/courses/cs2211/Asn/asn4$ ./bs_tree
[?2004l1024
5 Apple
$5
3 Banana
$3
5 Apple
$10
8 Cherry
$8
3 Banana
$15

5 Apple    $5
3 Banana    $3
8 Cherry    $8
[?2004hmwatt29@compute:~/courses/cs2211/Asn/asn4$ ./bs_tree 
[?2004l5
1 A
$1
2 B
$2
3 C
$3
4 D
$4
5 E
$5
6 F
$6Error: Array index out of bounds
Error: Array index out of bounds
Error: Array index out of bounds
Error: Array index out of bounds
1 A    $1
2 B    $2
[?2004hmwatt29@compute:~/courses/cs2211/Asn/asn4$ ./bs_tree 
[?2004l10
5 Apple
$5
5 Apple    $5
[?2004hmwatt29@compute:~/courses/cs2211/Asn/asn4$ ./bs_tree
[?2004l1024
1 A
$1
2 B
$2
3 C
$3
4 D
$4
5 E
$5

1 A    $1
2 B    $2
3 C    $3
4 D    $4
5 E    $5
[?2004hmwatt29@compute:~/courses/cs2211/Asn/asn4$ ./bs_tree
[?2004l1024
5 E
$5
4 D
$4
3 C
$3
2 B
$2
1 A
$1

1 A    $1
2 B    $2
3 C    $3
4 D    $4
5 E    $5
[?2004hmwatt29@compute:~/courses/cs2211/Asn/asn4$ exit
[?2004lexit

Script done on 2025-03-12 13:56:55-04:00 [COMMAND_EXIT_CODE="0"]
